### ISSUE TITLE
Running slower on more threads

### ISSUE THREAD

**Issue by pavlemarinkovic** [Illumina/Isaac4#10]
Hi,

I've been testing Isaac's performance on different data sets, and I've been getting some mixed results. Namely, when using smaller data sets (below ~40GB), 36 CPU threads perform significantly better than 16 threads, while when using larger sets (>80 GB), 16 threads perform the task in half the time 36 threads do. I've tried adding the --jobs argument to the command line, but I didn't see much improvement.

Can you give me some advice on how to tackle this issue?

Thanks in advance,
Pavle

**Comment by rpetrovski** [comment]
Isaac should scale linearly with CPU if the CPU is bottleneck at all stages. It is not clear from your post whether you are using the same hardware for 36 and 16 thread runs or not. My recommendation would be to use the same box on both occasions while limiting --jobs to 16 for the low-CPU run as opposite to utilizing a separate machine for that.

Before we go into complicated things, have you ruled out the basics? In particular, when running the same data multiple times on the same box, it is possible to have first run take longer than the subsequent run because the input data gets cached in RAM afterwards. 

To make sure our test don't suffer from IO caching side effects we normally perform the following command just before running isaac_align
sync; echo 3 > /proc/sys/vm/drop_caches

Since Isaac attempts to allocate quite a bit of memory including per-thread buffers, the care must be made that with high thread runs the system does not start swapping the pages out to the disk.

Also, it is important to make sure that the tested system is isolated from other influences. This includes that the environment is not shared with other users and that the input data, reference, Temp and output locations are not on a variable throughput/latency storage such as network mounted partitions, including off-box storages such as EBS provided by amazon cloud infrastructure.

Cloud services are special case in the sense that cloud instances must be made sure to not have neighbors sharing the same hardware and that the same instance is used for comparative runs.

Let me know how this goes and please post the details about your data(fastq? bcl?), reference (Human?) and the hardware.

Roman.

**Comment by pavlemarinkovic** [comment]
Sorry for the lack of details,
I'm running Isaac on Amazon instances so I don't have precise specs. The instances I was using were: c5.9xlarge (36 threads, 72 GB RAM, storage is EBS only), and m5.4xlarge (16 threads, 64 GB RAM, storage is EBS only). All of the resources of the instance were reserved for the task and there should not have been any sharing. I've ran it twice, and both times got the same results.

The reference I was using for all tests was GRCh38 (~3 GB)
And the files I was aligning that I got the mentioned results were fastq.gz paired-end reads WGS data (together ~80GB in size)

Command line: "-b isaac-inputs --reference-genome GRCh38.fa -f fastq-gz -m 50", were isaac-inputs was a directory containing the fastq.gz files.
Memory usage: Max 45.1 GB, Average 39.6GB
CPU usage: Max 78%, Average 38%
Processes: Max 54, Average 16
Swap: Max 712MB, Average 580MB

**Comment by pasmith50** [comment]
Your CPU usage suggest you are probably IO bound. What type of EBS volume are you using? GP2, ST1 ?
How big a volume do yo have since performance scales with the size?
Generally I use a stripped raid volume made up of four 1TB GP2 volumes.

**Comment by pavlemarinkovic** [comment]
Looks like there's something about "c" instances that makes them slower for for larger file sizes, though I cannot see what that thing is (it could be what pasmith50 pointed out, that the IO is bottlenecking). I've ran Isaac on the next higher "m" instance (m5.12xlarge) and it behaves much more in line with what would be expected.

Thanks guys!
